### ISSUE TITLE
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

### ISSUE THREAD

**Issue by yardstick17** [sbearben/chat-backend#2]
Running the cmd: 
```bash
python manage.py runserver
```
Resulting this error trace:

```bash
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/amkus/Projects/chat-backend/.venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Users/amkus/Projects/chat-backend/.venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/amkus/Projects/chat-backend/.venv/lib/python3.7/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/amkus/Projects/chat-backend/.venv/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 60, in execute
    super().execute(*args, **options)
  File "/Users/amkus/Projects/chat-backend/.venv/lib/python3.7/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/Users/amkus/Projects/chat-backend/.venv/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 67, in handle
    if not settings.DEBUG and not settings.ALLOWED_HOSTS:
  File "/Users/amkus/Projects/chat-backend/.venv/lib/python3.7/site-packages/django/conf/__init__.py", line 76, in __getattr__
    self._setup(name)
  File "/Users/amkus/Projects/chat-backend/.venv/lib/python3.7/site-packages/django/conf/__init__.py", line 63, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/amkus/Projects/chat-backend/.venv/lib/python3.7/site-packages/django/conf/__init__.py", line 161, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
```

**Comment by himanshu-patel-dev** [comment]
provide 
`SECRET_KEY = 'my-top-secret-random-string'` in `settings.py` of project.
